# Defer panic recover

## Defer
当函数执行到最后时，这些defer语句会按照逆序执行，最后该函数返回。

```go
func ReadWrite() bool {
    file.Open("file")
    defer file.Close()

    if failureX {
        return false
    }

    if failureY {
        return false
    }

    return true
}
```

## Panic 和 Recover

代码中应该尽量少有panic (最开始写go的时候，经常会用panic)

panic的介绍

是一个内建函数，可以中断原有的控制流程，进入一个令人恐慌的流程中。 当函数F调用panic，函数F的执行被中断，但是F中的延迟函数会正常执行，然后F返回到调用它的地方。 在调用的地方，F的行为就像调用了panic。 这一过程继续向上，直到发生panic的goroutine中所有调用的函数返回，此时程序退出。 恐慌可以直接调用panic产生。也可以由运行时错误产生，例如访问越界的数组。


recover的介绍

是一个内建的函数，可以让进入令人恐慌的流程中的goroutine恢复过来。 recover仅在延迟函数中有效。在正常的执行过程中，调用recover会返回nil，并且没有其它任何效果。 如果当前的goroutine陷入恐慌，调用recover可以捕获到panic的输入值，并且恢复正常的执行。

下面这个函数检查作为其参数的函数在执行时是否会产生panic：

```go
func throwsPanic(f func()) (b bool) {

    defer func() {
        if x := recover(); x != nil {
            b = true
        }
    }()

    f() //执行函数f，如果f中出现了panic，那么就可以恢复回来

    return
}

```

一个demo

```go
import (
    "fmt"
)

func f1() {
    defer func() {
        if x := recover(); x != nil {
            fmt.Println("Recover:", x)
        }
    }()
    fmt.Println("f1")
    defer func() {
        fmt.Println("defer before f2")
    }()
    f2()
    defer func() {
        fmt.Println("defer after f2")
    }()
    fmt.Println("after f2")
}

func f2() {
    fmt.Println("f2")
    panic("f2")
}

func main() {
    f1()
}
```

返回结果：

```go
f1
f2
defer before f2
Recover: f2
```


简单总结：

- panic后的所有代码都不会再执行了，即使通过recover进行了恢复。
- 在recover之前，已经defer过的代码块会按倒序进行执行(也就是panic后的defer也不会执行)。
- 在recover之后，函数就执行了return操作，也就是不会再执行当前函数里的代码了。


